-- TABLA INCIDENTE BANDERA
SELECT distinct m.INCIDENTE_BANDERA FROM gd_esquema.Maestra m
where NOT m.INCIDENTE_BANDERA IS NULL
-- TABLA TIPO ACCIDENTE
SELECT distinct m.INCIDENTE_TIPO FROM gd_esquema.Maestra m
where NOT m.INCIDENTE_TIPO IS NULL

-- TABLA POSICION NEUMATICO
SELECT distinct m.NEUMATICO1_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO1_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO2_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO2_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO3_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO3_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO4_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO2_POSICION_NUEVO IS NULL
-- TABLA TIPO NEUMATICO
SELECT distinct m.NEUMATICO1_TIPO_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO1_TIPO_NUEVO IS NULL
-- TABLA PAIS_NACIONALIDAD
SELECT distinct m.CIRCUITO_PAIS FROM gd_esquema.Maestra m
where NOT m.CIRCUITO_PAIS IS NULL
UNION
SELECT distinct m.ESCUDERIA_NACIONALIDAD FROM gd_esquema.Maestra m
where NOT m.ESCUDERIA_NACIONALIDAD IS NULL
UNION
SELECT distinct m.PILOTO_NACIONALIDAD FROM gd_esquema.Maestra m
where NOT m.PILOTO_NACIONALIDAD IS NULL

-- TABLA TIPO SECTOR
SELECT distinct m.SECTO_TIPO FROM gd_esquema.Maestra m
where NOT m.SECTO_TIPO IS NULL 

-- TABLA CLIMA
SELECT distinct m.CARRERA_CLIMA FROM gd_esquema.Maestra m
where NOT m.CARRERA_CLIMA IS NULL 




