-- TABLA INCIDENTE BANDERA
SELECT distinct m.INCIDENTE_BANDERA FROM gd_esquema.Maestra m
where NOT m.INCIDENTE_BANDERA IS NULL
-- TABLA TIPO ACCIDENTE
SELECT distinct m.INCIDENTE_TIPO FROM gd_esquema.Maestra m
where NOT m.INCIDENTE_TIPO IS NULL

-- TABLA POSICION NEUMATICO
SELECT distinct m.NEUMATICO1_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO1_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO2_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO2_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO3_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO3_POSICION_NUEVO IS NULL
UNION
SELECT distinct m.NEUMATICO4_POSICION_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO2_POSICION_NUEVO IS NULL
-- TABLA TIPO NEUMATICO
SELECT distinct m.NEUMATICO1_TIPO_NUEVO FROM gd_esquema.Maestra m
where NOT m.NEUMATICO1_TIPO_NUEVO IS NULL
-- TABLA PAIS_NACIONALIDAD
SELECT distinct m.CIRCUITO_PAIS FROM gd_esquema.Maestra m
where NOT m.CIRCUITO_PAIS IS NULL
UNION
SELECT distinct m.ESCUDERIA_NACIONALIDAD FROM gd_esquema.Maestra m
where NOT m.ESCUDERIA_NACIONALIDAD IS NULL
UNION
SELECT distinct m.PILOTO_NACIONALIDAD FROM gd_esquema.Maestra m
where NOT m.PILOTO_NACIONALIDAD IS NULL

-- TABLA TIPO SECTOR
SELECT distinct m.SECTO_TIPO FROM gd_esquema.Maestra m
where NOT m.SECTO_TIPO IS NULL 

-- TABLA CLIMA
SELECT distinct m.CARRERA_CLIMA FROM gd_esquema.Maestra m
where NOT m.CARRERA_CLIMA IS NULL 

SELECT distinct CODIGO_CARRERA, AUTO_MODELO, AUTO_NUMERO, TELE_MOTOR_MODELO, TELE_MOTOR_NRO_SERIE, TELE_CAJA_MODELO, TELE_CAJA_NRO_SERIE FROM gd_esquema.Maestra
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL AND TELE_CAJA_NRO_SERIE IS NOT NULL

SELECT distinct CODIGO_CARRERA, AUTO_MODELO, AUTO_NUMERO, TELE_MOTOR_MODELO, TELE_MOTOR_NRO_SERIE FROM gd_esquema.Maestra
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL AND TELE_CAJA_NRO_SERIE IS NOT NULL


SELECT distinct CODIGO_CARRERA, AUTO_MODELO, AUTO_NUMERO, TELE_CAJA_MODELO, TELE_CAJA_NRO_SERIE FROM gd_esquema.Maestra
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL AND TELE_CAJA_NRO_SERIE IS NOT NULL


SELECT distinct CODIGO_SECTOR, INCIDENTE_TIPO, INCIDENTE_TIEMPO, INCIDENTE_BANDERA FROM gd_esquema.Maestra
WHERE INCIDENTE_TIEMPO IS NOT NULL

SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA FROM gd_esquema.Maestra


--TEMPORAL MOTOR

SELECT distinct TELE_MOTOR_MODELO, TELE_MOTOR_NRO_SERIE, AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA FROM gd_esquema.Maestra
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL


--TEMPORAL CAJA CAMBIOS

SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_CAJA_MODELO, TELE_CAJA_NRO_SERIE FROM gd_esquema.Maestra
WHERE TELE_CAJA_NRO_SERIE IS NOT NULL

--TEMPORAL FRENOS 1, 2, 3, Y 4

SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_FRENO1_NRO_SERIE, TELE_FRENO1_TAMANIO_DISCO, TELE_FRENO1_POSICION FROM gd_esquema.Maestra
WHERE TELE_FRENO1_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_FRENO2_NRO_SERIE, TELE_FRENO2_TAMANIO_DISCO, TELE_FRENO2_POSICION FROM gd_esquema.Maestra
WHERE TELE_FRENO2_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_FRENO3_NRO_SERIE, TELE_FRENO3_TAMANIO_DISCO, TELE_FRENO3_POSICION FROM gd_esquema.Maestra
WHERE TELE_FRENO3_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_FRENO4_NRO_SERIE, TELE_FRENO4_TAMANIO_DISCO, TELE_FRENO4_POSICION FROM gd_esquema.Maestra
WHERE TELE_FRENO4_NRO_SERIE IS NOT NULL
ORDER BY 1,2,3

--TEMPORAL NEUMATICOS 1, 2, 3 Y 4

-- HARIA FALTA EL TIPO EN LA TELEMETRIA

SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_NEUMATICO1_NRO_SERIE, TELE_NEUMATICO1_POSICION FROM gd_esquema.Maestra
WHERE TELE_NEUMATICO1_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_NEUMATICO2_NRO_SERIE, TELE_NEUMATICO2_POSICION FROM gd_esquema.Maestra
WHERE TELE_NEUMATICO2_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_NEUMATICO3_NRO_SERIE, TELE_NEUMATICO3_POSICION FROM gd_esquema.Maestra
WHERE TELE_NEUMATICO3_NRO_SERIE IS NOT NULL
UNION
SELECT distinct AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA, TELE_NEUMATICO4_NRO_SERIE, TELE_NEUMATICO4_POSICION FROM gd_esquema.Maestra
WHERE TELE_NEUMATICO4_NRO_SERIE IS NOT NULL
ORDER BY 1,2,3


SELECT distinct TELE_NEUMATICO2_NRO_SERIE, AUTO_MODELO, AUTO_NUMERO, CODIGO_CARRERA FROM gd_esquema.Maestra
WHERE TELE_NEUMATICO2_NRO_SERIE IS NOT NULL AND TELE_NEUMATICO2_NRO_SERIE IN (
SELECT distinct NEUMATICO2_NRO_SERIE_NUEVO FROM gd_esquema.Maestra
WHERE NEUMATICO2_NRO_SERIE_NUEVO IS NOT NULL)
