/*Medicion vuelta */
select e.ESCUDERIA_ID, tel.TELE_NUMERO_DE_VUELTA,ci.CIRCUITO_ID,ac.AUTO_CARRERA_ID,year(ca.CARRERA_FECHA) as [Año],
(select max(TELE_TIEMPO_DE_VUELTA) from GDD_EXPRESS.Telemetria where TELE_NUMERO_DE_VUELTA=tel.TELE_NUMERO_DE_VUELTA and TELE_AUTO_CARRERA_ID=ac.AUTO_CARRERA_ID) as [Tiempo de vuelta],
(select max(TELE_COMBUSTIBLE)-min(TELE_COMBUSTIBLE) from GDD_EXPRESS.Telemetria where TELE_NUMERO_DE_VUELTA=tel.TELE_NUMERO_DE_VUELTA and TELE_AUTO_CARRERA_ID=ac.AUTO_CARRERA_ID) as [Consumo de combustible]
from GDD_EXPRESS.Escuderia e
join GDD_EXPRESS.Auto a on a.AUTO_ESCUDERIA_ID=e.ESCUDERIA_ID
join GDD_EXPRESS.Auto_Carrera ac on ac.AUTO_ID=a.AUTO_ID
join GDD_EXPRESS.Carrera ca on ca.CARRERA_ID=ac.CARRERA_ID
join GDD_EXPRESS.Circuito ci on ci.CIRCUITO_ID=ca.CARRERA_CIRCUITO_ID
join GDD_EXPRESS.Telemetria tel on tel.TELE_AUTO_CARRERA_ID=ac.AUTO_CARRERA_ID
group by e.ESCUDERIA_ID, tel.TELE_NUMERO_DE_VUELTA,ci.CIRCUITO_ID,ac.AUTO_CARRERA_ID,year(ca.CARRERA_FECHA)
order by ac.AUTO_CARRERA_ID
